nav:
- Actisô ( Lá): Actisô ( Lá)/Actisô ( Lá).md
- Actisô (Lá): Actisô (Lá)/Actisô (Lá).md
- Ba Kích (Rễ): Ba Kích (Rễ)/Ba Kích (Rễ).md
- Bán Hạ: Bán Hạ/Bán Hạ.md
- Bìm Bìm Biếc (Hạt): Bìm Bìm Biếc (Hạt)/Bìm Bìm Biếc (Hạt).md
- Bình Vôi(Củ): Bình Vôi(Củ)/Bình Vôi(Củ).md
- Bạc Hà: Bạc Hà/Bạc Hà.md
- Bạch Hoa Xà Thiệt Thảo (Toàn Cây): Bạch Hoa Xà Thiệt Thảo (Toàn Cây)/Bạch Hoa Xà
    Thiệt Thảo (Toàn Cây).md
- Bạch Thược (Rễ): Bạch Thược (Rễ)/Bạch Thược (Rễ).md
- Bạch Truật (Thân Rễ): Bạch Truật (Thân Rễ)/Bạch Truật (Thân Rễ).md
- Bạch Tật Lê (Quả): Bạch Tật Lê (Quả)/Bạch Tật Lê (Quả).md
- Bồ Bồ (Thân, Cành Mang Lá Và Hoa): Bồ Bồ (Thân, Cành Mang Lá Và Hoa)/Bồ Bồ (Thân,
    Cành Mang Lá Và Hoa).md
- Bồ Công Anh (Lá, Toàn Cây Trừ Rễ): Bồ Công Anh (Lá, Toàn Cây Trừ Rễ)/Bồ Công Anh
    (Lá, Toàn Cây Trừ Rễ).md
- Cam Thảo (Rễ Và Thân Rễ): Cam Thảo (Rễ Và Thân Rễ)/Cam Thảo (Rễ Và Thân Rễ).md
- Cam Thảo Nam (Toàn Cây): Cam Thảo Nam (Toàn Cây)/Cam Thảo Nam (Toàn Cây).md
- Cau (Hạt): Cau (Hạt)/Cau (Hạt).md
- Cau (Vỏ): Cau (Vỏ)/Cau (Vỏ).md
- Chè Vằng (Lá): Chè Vằng (Lá)/Chè Vằng (Lá).md
- Cà Độc Dược (Hoa): Cà Độc Dược (Hoa)/Cà Độc Dược (Hoa).md
- Cà Độc Dược (Lá): Cà Độc Dược (Lá)/Cà Độc Dược (Lá).md
- Cánh Kiến Trắng (Nhựa): Cánh Kiến Trắng (Nhựa)/Cánh Kiến Trắng (Nhựa).md
- Cát Cánh (Rễ): Cát Cánh (Rễ)/Cát Cánh (Rễ).md
- Cát Sâm (Rễ): Cát Sâm (Rễ)/Cát Sâm (Rễ).md
- Cây Hoa Súng (Củ Súng): Cây Hoa Súng (Củ Súng)/Cây Hoa Súng (Củ Súng).md
- Cây Kim Ngân - Nụ Hoa: Cây Kim Ngân - Nụ Hoa/Cây Kim Ngân - Nụ Hoa.md
- Cây Kim Tiền Thảo - Phần Trên Mặt Đất: Cây Kim Tiền Thảo - Phần Trên Mặt Đất/Cây
    Kim Tiền Thảo - Phần Trên Mặt Đất.md
- Cây Ổi (Lá): Cây Ổi (Lá)/Cây Ổi (Lá).md
- Cúc Gai (Quả): Cúc Gai (Quả)/Cúc Gai (Quả).md
- Cần Tây (Quả): Cần Tây (Quả)/Cần Tây (Quả).md
- Cỏ Ngọt (Lá): Cỏ Ngọt (Lá)/Cỏ Ngọt (Lá).md
- Cỏ Nhọ Nồi (Phần Cây Trên Mặt Đất): Cỏ Nhọ Nồi (Phần Cây Trên Mặt Đất)/Cỏ Nhọ Nồi
    (Phần Cây Trên Mặt Đất).md
- Cỏ Tranh (Thân Rễ): Cỏ Tranh (Thân Rễ)/Cỏ Tranh (Thân Rễ).md
- Cỏ Xước (Rễ): Cỏ Xước (Rễ)/Cỏ Xước (Rễ).md
- Dâu (Quả): Dâu (Quả)/Dâu (Quả).md
- Dâu (Vỏ Rễ): Dâu (Vỏ Rễ)/Dâu (Vỏ Rễ).md
- Dây Thìa Canh (Dây, Lá): Dây Thìa Canh (Dây, Lá)/Dây Thìa Canh (Dây, Lá).md
- Dây Đau Xương (Thân): Dây Đau Xương (Thân)/Dây Đau Xương (Thân).md
- Gừng (Thân Rễ): Gừng (Thân Rễ)/Gừng (Thân Rễ).md
- Hoàng Kỳ (Rễ): Hoàng Kỳ (Rễ)/Hoàng Kỳ (Rễ).md
- Hoàng Liên (Thân Rễ): Hoàng Liên (Thân Rễ)/Hoàng Liên (Thân Rễ).md
- Huyết Giác (Lõi Gỗ): Huyết Giác (Lõi Gỗ)/Huyết Giác (Lõi Gỗ).md
- Hy Thiêm (Bộ Phận Trên Mặt Đất): Hy Thiêm (Bộ Phận Trên Mặt Đất)/Hy Thiêm (Bộ Phận
    Trên Mặt Đất).md
- Hy Thiêm - Dược Liệu Là Bộ Phận Trên Mặt Đất Phơi Khô: Hy Thiêm - Dược Liệu Là Bộ
    Phận Trên Mặt Đất Phơi Khô/Hy Thiêm - Dược Liệu Là Bộ Phận Trên Mặt Đất Phơi Khô.md
- Hương Gia Bì (Vỏ Rễ): Hương Gia Bì (Vỏ Rễ)/Hương Gia Bì (Vỏ Rễ).md
- Hương Phụ (Thân Rễ): Hương Phụ (Thân Rễ)/Hương Phụ (Thân Rễ).md
- Hồ Tiêu (Quả): Hồ Tiêu (Quả)/Hồ Tiêu (Quả).md
- Hồng Hoa (Hoa): Hồng Hoa (Hoa)/Hồng Hoa (Hoa).md
- Khiếm Thực (Hạt): Khiếm Thực (Hạt)/Khiếm Thực (Hạt).md
- Khoản Đông Hoa (Cụm Hoa Chưa Nở Đã Phơi Sấy Khô): Khoản Đông Hoa (Cụm Hoa Chưa Nở
    Đã Phơi Sấy Khô)/Khoản Đông Hoa (Cụm Hoa Chưa Nở Đã Phơi Sấy Khô).md
- Khổ Hạnh Nhân: Khổ Hạnh Nhân/Khổ Hạnh Nhân.md
- Kim Anh ( Quả): Kim Anh ( Quả)/Kim Anh ( Quả).md
- Kim Ngân (Cuộng): Kim Ngân (Cuộng)/Kim Ngân (Cuộng).md
- Kim Ngân (Hoa): Kim Ngân (Hoa)/Kim Ngân (Hoa).md
- Kinh Giới (Thân Cây Trên Mặt Đất): Kinh Giới (Thân Cây Trên Mặt Đất)/Kinh Giới (Thân
    Cây Trên Mặt Đất).md
- Ké Đầu Ngựa (Qủa): Ké Đầu Ngựa (Qủa)/Ké Đầu Ngựa (Qủa).md
- Kê Huyết Đằng (Thân): Kê Huyết Đằng (Thân)/Kê Huyết Đằng (Thân).md
- Linh Chi: Linh Chi/Linh Chi.md
- Liên Kiều (Quả): Liên Kiều (Quả)/Liên Kiều (Quả).md
- Long Nha Thảo( Phần Trên Mặt Đất): Long Nha Thảo( Phần Trên Mặt Đất)/Long Nha Thảo(
    Phần Trên Mặt Đất).md
- Long Nhãn (Cùi): Long Nhãn (Cùi)/Long Nhãn (Cùi).md
- Long Đởm (Rễ Và Thân Rễ): Long Đởm (Rễ Và Thân Rễ)/Long Đởm (Rễ Và Thân Rễ).md
- Lá Hen (Dùng Lá): Lá Hen (Dùng Lá)/Lá Hen (Dùng Lá).md
- Lá Lốt (Phần Trên Mặt Đất Tươi Hay Phơi, Sấy Khô): Lá Lốt (Phần Trên Mặt Đất Tươi
    Hay Phơi, Sấy Khô)/Lá Lốt (Phần Trên Mặt Đất Tươi Hay Phơi, Sấy Khô).md
- Lá Móng: Lá Móng/Lá Móng.md
- Lô Hội (Nhựa): Lô Hội (Nhựa)/Lô Hội (Nhựa).md
- Lạc Tiên: Lạc Tiên/Lạc Tiên.md
- Ma Hoàng (Bộ Phận Trên Mặt Đất): Ma Hoàng (Bộ Phận Trên Mặt Đất)/Ma Hoàng (Bộ Phận
    Trên Mặt Đất).md
- Mâm Xôi (Quả): Mâm Xôi (Quả)/Mâm Xôi (Quả).md
- Mã Tiền (Hạt): Mã Tiền (Hạt)/Mã Tiền (Hạt).md
- Mã Đề (Hạt): Mã Đề (Hạt)/Mã Đề (Hạt).md
- Mã Đề (Lá): Mã Đề (Lá)/Mã Đề (Lá).md
- Măng Cụt (Vỏ Quả): Măng Cụt (Vỏ Quả)/Măng Cụt (Vỏ Quả).md
- Mướp Đắng (Quả): Mướp Đắng (Quả)/Mướp Đắng (Quả).md
- Mạch Môn (Rễ): Mạch Môn (Rễ)/Mạch Môn (Rễ).md
- Mạn Kinh Tử (Quả): Mạn Kinh Tử (Quả)/Mạn Kinh Tử (Quả).md
- Mộc Hương (Rễ): Mộc Hương (Rễ)/Mộc Hương (Rễ).md
- Mộc Qua (Quả): Mộc Qua (Quả)/Mộc Qua (Quả).md
- Mộc Tặc (Phần Trên Mặt Đất): Mộc Tặc (Phần Trên Mặt Đất)/Mộc Tặc (Phần Trên Mặt
    Đất).md
- Nga Truật (Thân Rễ): Nga Truật (Thân Rễ)/Nga Truật (Thân Rễ).md
- Nghệ (Thân Rễ): Nghệ (Thân Rễ)/Nghệ (Thân Rễ).md
- Ngoi (Lá): Ngoi (Lá)/Ngoi (Lá).md
- Ngành Ngạnh (Lá): Ngành Ngạnh (Lá)/Ngành Ngạnh (Lá).md
- Ngũ Gia Bì Chân Chim (Vỏ Thân, Vỏ Cành): Ngũ Gia Bì Chân Chim (Vỏ Thân, Vỏ Cành)/Ngũ
    Gia Bì Chân Chim (Vỏ Thân, Vỏ Cành).md
- Ngũ Gia Bì Gai (Vỏ Rễ, Vỏ Thân): Ngũ Gia Bì Gai (Vỏ Rễ, Vỏ Thân)/Ngũ Gia Bì Gai
    (Vỏ Rễ, Vỏ Thân).md
- Ngũ Gia Bì Hương (Vỏ Rễ, Vỏ Thân): Ngũ Gia Bì Hương (Vỏ Rễ, Vỏ Thân)/Ngũ Gia Bì
    Hương (Vỏ Rễ, Vỏ Thân).md
- Ngũ Vị Tử ( Quả): Ngũ Vị Tử ( Quả)/Ngũ Vị Tử ( Quả).md
- Ngải Cứu: Ngải Cứu/Ngải Cứu.md
- Ngọc Trúc (Thân Rễ): Ngọc Trúc (Thân Rễ)/Ngọc Trúc (Thân Rễ).md
- Nhàu (Rễ): Nhàu (Rễ)/Nhàu (Rễ).md
- Nhân Sâm (Thân Rễ Và Rễ): Nhân Sâm (Thân Rễ Và Rễ)/Nhân Sâm (Thân Rễ Và Rễ).md
- Nhân Trần (Thân, Cành, Lá, Hoa): Nhân Trần (Thân, Cành, Lá, Hoa)/Nhân Trần (Thân,
    Cành, Lá, Hoa).md
- Nhân Trần Tía (Thân, Cành, Lá, Hóa): Nhân Trần Tía (Thân, Cành, Lá, Hóa)/Nhân Trần
    Tía (Thân, Cành, Lá, Hóa).md
- Nhục Thung Dung (Thân): Nhục Thung Dung (Thân)/Nhục Thung Dung (Thân).md
- Nhục Đậu Khấu (Hạt): Nhục Đậu Khấu (Hạt)/Nhục Đậu Khấu (Hạt).md
- Náng Hoa Trắng (Lá): Náng Hoa Trắng (Lá)/Náng Hoa Trắng (Lá).md
- Nân Nghệ (Thân Rễ): Nân Nghệ (Thân Rễ)/Nân Nghệ (Thân Rễ).md
- Núc Nác (Vỏ Thân): Núc Nác (Vỏ Thân)/Núc Nác (Vỏ Thân).md
- Phòng Kỷ (Rễ): Phòng Kỷ (Rễ)/Phòng Kỷ (Rễ).md
- Phòng Phong (Rễ): Phòng Phong (Rễ)/Phòng Phong (Rễ).md
- Phụ Tử (Rễ Củ Nhánh Đã Phơi Hay Sấy Khô Của Cầy Ô Đầu ): Phụ Tử (Rễ Củ Nhánh Đã
    Phơi Hay Sấy Khô Của Cầy Ô Đầu )/Phụ Tử (Rễ Củ Nhánh Đã Phơi Hay Sấy Khô Của Cầy
    Ô Đầu ).md
- Qua Lâu (Quả): Qua Lâu (Quả)/Qua Lâu (Quả).md
- Quế (Cành): Quế (Cành)/Quế (Cành).md
- Rau Má (Toàn Cây): Rau Má (Toàn Cây)/Rau Má (Toàn Cây).md
- Rau Đắng Đất (Toàn Cây): Rau Đắng Đất (Toàn Cây)/Rau Đắng Đất (Toàn Cây).md
- Riềng (Thân Rễ): Riềng (Thân Rễ)/Riềng (Thân Rễ).md
- Râu Ngô (Râu Ngô): Râu Ngô (Râu Ngô)/Râu Ngô (Râu Ngô).md
- Rẻ Quạt (Thân Rễ): Rẻ Quạt (Thân Rễ)/Rẻ Quạt (Thân Rễ).md
- Sa Nhân (Quả): Sa Nhân (Quả)/Sa Nhân (Quả).md
- Sen (Hạt): Sen (Hạt)/Sen (Hạt).md
- Sài Hồ (Rễ): Sài Hồ (Rễ)/Sài Hồ (Rễ).md
- Thanh Bì (Vỏ Quả Xanh): Thanh Bì (Vỏ Quả Xanh)/Thanh Bì (Vỏ Quả Xanh).md
- Thanh Cao Hoa Vàng (Lá): Thanh Cao Hoa Vàng (Lá)/Thanh Cao Hoa Vàng (Lá).md
- Thiên Ma (Thân Rễ): Thiên Ma (Thân Rễ)/Thiên Ma (Thân Rễ).md
- Thiên Môn Đông (Rễ): Thiên Môn Đông (Rễ)/Thiên Môn Đông (Rễ).md
- Thiên Trúc Hoàng: Thiên Trúc Hoàng/Thiên Trúc Hoàng.md
- Thông Thảo (Lõi Thân): Thông Thảo (Lõi Thân)/Thông Thảo (Lõi Thân).md
- Thăng Ma (Thân Rễ): Thăng Ma (Thân Rễ)/Thăng Ma (Thân Rễ).md
- Thương Truật (Thân Rễ): Thương Truật (Thân Rễ)/Thương Truật (Thân Rễ).md
- Thạch Xương Bồ (Thân Rễ): Thạch Xương Bồ (Thân Rễ)/Thạch Xương Bồ (Thân Rễ).md
- Thảo Quyết Minh (Hạt): Thảo Quyết Minh (Hạt)/Thảo Quyết Minh (Hạt).md
- Thảo Quả (Quả): Thảo Quả (Quả)/Thảo Quả (Quả).md
- Thị Đế: Thị Đế/Thị Đế.md
- Thỏ Ty Tử: Thỏ Ty Tử/Thỏ Ty Tử.md
- Thổ Hoàng Liên (Thân Rễ): Thổ Hoàng Liên (Thân Rễ)/Thổ Hoàng Liên (Thân Rễ).md
- Thổ Phục Linh (Thân Rễ): Thổ Phục Linh (Thân Rễ)/Thổ Phục Linh (Thân Rễ).md
- Tiền Hồ (Rễ): Tiền Hồ (Rễ)/Tiền Hồ (Rễ).md
- Tri Mẫu (Thân Rễ): Tri Mẫu (Thân Rễ)/Tri Mẫu (Thân Rễ).md
- Trinh Nữ Hoàng Cung (Lá): Trinh Nữ Hoàng Cung (Lá)/Trinh Nữ Hoàng Cung (Lá).md
- Tràm (Cành Và Lá): Tràm (Cành Và Lá)/Tràm (Cành Và Lá).md
- Trạch Tả (Thân Rễ): Trạch Tả (Thân Rễ)/Trạch Tả (Thân Rễ).md
- Tía Tô (Lá): Tía Tô (Lá)/Tía Tô (Lá).md
- Tía Tô (Quả): Tía Tô (Quả)/Tía Tô (Quả).md
- Tía Tô (Thân): Tía Tô (Thân)/Tía Tô (Thân).md
- Tía Tô( Thân): Tía Tô( Thân)/Tía Tô( Thân).md
- Tô Mộc: Tô Mộc/Tô Mộc.md
- Tỏi (Củ): Tỏi (Củ)/Tỏi (Củ).md
- Tục Đoạn (Rễ): Tục Đoạn (Rễ)/Tục Đoạn (Rễ).md
- Tỳ Giải (Thân Rễ): Tỳ Giải (Thân Rễ)/Tỳ Giải (Thân Rễ).md
- Uy Linh Tiên (Rễ Và Thân Rễ): Uy Linh Tiên (Rễ Và Thân Rễ)/Uy Linh Tiên (Rễ Và Thân
    Rễ).md
- Viễn Chí (Rễ): Viễn Chí (Rễ)/Viễn Chí (Rễ).md
- Vàng Đắng (Thân): Vàng Đắng (Thân)/Vàng Đắng (Thân).md
- Vông Nem ( Lá): Vông Nem ( Lá)/Vông Nem ( Lá).md
- Vọng Cách (Lá): Vọng Cách (Lá)/Vọng Cách (Lá).md
- Vối ( Nụ Hoa ): Vối ( Nụ Hoa )/Vối ( Nụ Hoa ).md
- Vối (Lá): Vối (Lá)/Vối (Lá).md
- Vừng Đen (Hạt): Vừng Đen (Hạt)/Vừng Đen (Hạt).md
- Xuyên Khung (Thân Rễ): Xuyên Khung (Thân Rễ)/Xuyên Khung (Thân Rễ).md
- Xuyên Tiêu (Quả): Xuyên Tiêu (Quả)/Xuyên Tiêu (Quả).md
- Xuyên Tâm Liên (Thân Rễ): Xuyên Tâm Liên (Thân Rễ)/Xuyên Tâm Liên (Thân Rễ).md
- Xà Sàng (Quả): Xà Sàng (Quả)/Xà Sàng (Quả).md
- Xích Thược (Rễ): Xích Thược (Rễ)/Xích Thược (Rễ).md
- Xích Đồng Nam (Rễ): Xích Đồng Nam (Rễ)/Xích Đồng Nam (Rễ).md
- Xương Bồ: Xương Bồ/Xương Bồ.md
- index: index.md
- Ích Mẫu: Ích Mẫu/Ích Mẫu.md
- Ích Mẫu (Phần Trên Mặt Đất): Ích Mẫu (Phần Trên Mặt Đất)/Ích Mẫu (Phần Trên Mặt
    Đất).md
- Ích Trí (Quả): Ích Trí (Quả)/Ích Trí (Quả).md
- Ô Dược (Rễ): Ô Dược (Rễ)/Ô Dược (Rễ).md
- Ô Đầu (Rễ Củ): Ô Đầu (Rễ Củ)/Ô Đầu (Rễ Củ).md
- Đan Sâm (Rễ Và Thân Rễ): Đan Sâm (Rễ Và Thân Rễ)/Đan Sâm (Rễ Và Thân Rễ).md
- Đào (Hạt): Đào (Hạt)/Đào (Hạt).md
- Đăng Tâm Thảo (Ruột Thân): Đăng Tâm Thảo (Ruột Thân)/Đăng Tâm Thảo (Ruột Thân).md
- Đơn Kim (Lá): Đơn Kim (Lá)/Đơn Kim (Lá).md
- Đơn Lá Đỏ: Đơn Lá Đỏ/Đơn Lá Đỏ.md
- Đương Quy (Rễ): Đương Quy (Rễ)/Đương Quy (Rễ).md
- Đại Hoàng (Thân Rễ): Đại Hoàng (Thân Rễ)/Đại Hoàng (Thân Rễ).md
- Đảng Sâm (Rễ): Đảng Sâm (Rễ)/Đảng Sâm (Rễ).md
- Đậu Ván Trắng (Hạt): Đậu Ván Trắng (Hạt)/Đậu Ván Trắng (Hạt).md
- Đậu Đen (Hạt): Đậu Đen (Hạt)/Đậu Đen (Hạt).md
- Địa Du (Rễ): Địa Du (Rễ)/Địa Du (Rễ).md
- Đỗ Trọng (Vỏ Thân): Đỗ Trọng (Vỏ Thân)/Đỗ Trọng (Vỏ Thân).md
site_name: My Project
theme:
  name: material
