name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: pip install mkdocs-material[imaging] 
      - run: pip install mkdocs-glightbox
      - run: pip install mkdocstrings
      - run: pip install markdown-exec
      - run: pip install mkdocs-awesome-pages-plugin
      - run: pip install mkdocs-categories-plugin 
      - run: pip install mkdocs-mermaid2-plugin
      - run: mkdocs build
      - name: Insert Google AdSense code
        run: |
          find site -name '*.html' -exec sed -i 's|</head>|<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1440105407870599" crossorigin="anonymous"></script></head>|' {} \;
      - run: mkdocs gh-deploy --force
